### ISSUE TITLE
高可用

### ISSUE THREAD

**Issue by deep011** [anewhuahua/bilitw#1]
hi，咨询一下，你们的tw高可用是怎么做的？

**Comment by anewhuahua** [comment]
写tw的agent去 监视sentinel p/sub

**Comment by deep011** [comment]
如果集群有多个tw的话，你们客户端怎么选择选择哪个tw的？tw前端有用lvs吗。

**Comment by deep011** [comment]
如果有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果一个集群有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果一个集群有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果一个集群有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果一个集群有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by deep011** [comment]
如果一个集群有多个tw的话，你们客户端怎么选择选择哪个tw的？

**Comment by anewhuahua** [comment]
nginx 方式， 哪个tw worker accept走就哪个服务

**Comment by deep011** [comment]
那你们的redis服务也是三层:nginx+tw+redis？

**Comment by anewhuahua** [comment]
yes
